### ISSUE TITLE
The commands shown on https://github.com/build2/cxx20-modules-examples causes compile errors

### ISSUE THREAD

**Issue by JungHong** [build2/cxx20-modules-examples#1]
The following (as posted on https://github.com/build2/cxx20-modules-examples)
causes compile errors with either g++ version 11 or version 12.
build2 was reinstalled after changing g++ version.

    git clone https://github.com/build2/cxx20-modules-examples.git
    cd cxx20-modules-examples

    bdep init -C @gcc cc config.cxx=g++ config.cxx.translate_include=all-importable
    bdep update @gcc

$ lsb_release -a
Ubuntu 22.04.1 LTS

$ g++ --version
g++ (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0

$ bdep --version
bdep 0.15.0
libbpkg 0.15.0
libbutl 0.15.0

$ git clone https://github.com/build2/cxx20-modules-examples
$ cd cxx20-modules-examples/
$ bdep init -C @gcc cc config.cxx=g++ config.cxx.translate_include=all-importable
$ bdep update @gcc

...

In module imported at /home/xxxx/cxx20-modules-examples/hello-library-header/libhello-header/tests/basics/driver.cxx:7:1:
/home/xxxx/cxx20-modules-examples/hello-library-header/libhello-header/libhello/hello.hxx: error: import ‘/usr/include/c++/12/string_view’ has CRC mismatch
In module imported at /home/xxxx/cxx20-modules-examples/hello-library-header/libhello-header/libhello/hello.hxx:8:1,
of module /home/xxxx/cxx20-modules-examples/hello-library-header/libhello-header/libhello/hello.hxx, imported at /home/xxxx/tmp/junk-dir/cxx20-modules-examples/hello-library-header/libhello-header/tests/basics/driver.cxx:7:
/home/xxxx/cxx20-modules-examples/hello-library-header/libhello-header/libhello/check.hxx: error: import ‘/usr/include/c++/12/string_view’ has CRC mismatch

**Comment by boris-kolpackov** [comment]
These are GCC bugs. You can try to narrow the header "importability" as a workarounds. You can see all the workarounds we currently (as of GCC 12) have to apply in the https://github.com/build2/cxx20-modules-examples/blob/master/test script.

> build2 was reinstalled after changing g++ version.

You didn't really need to do this, `build2` built with one compiler/version can be used with all the others.

**Comment by JungHong** [comment]
Thank you.  

I am new to build2 and I am overwhelmed.  Could someone please make the posted examples compile with g++ 12 ?  That would make it better for novices like me.

In the meantime, I will go to the ..../blob/master/test script and see, per your suggestions.

**Comment by JungHong** [comment]
This was done on an Ubuntu system, with build2 version 0.15.0, and g++ version 12.2.0.

$ lsb_release -a
Description:	Ubuntu 22.04.1 LTS

$ b --version
build2 0.15.0
libbutl 0.15.0

$ g++ --version
g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0

The test script at cxx20-modules-examples/test compiles the source files and executes to completion if :

1.  cd ./cxx20-modules-examples/hello-partition/hello/hello-format.mxx

2.  The string concatinations were changed to append

    //  ./hello-partition/hello/hello-format.mxx
    export module hello:format;

    import <string>;
    import <string_view>;

    export namespace hello
    {
      std::string
      format_hello (const std::string_view& name)
      {
        std::string str_hello{"Hello "};                         // changed line
        return str_hello.append(name).append("!");  // changed line
      }
    }

3.  ./test g++ -fmodules-ts  -std=c++23

**Comment by JungHong** [comment]
Correction:

1. cd ./cxx20-modules-examples/

**Comment by boris-kolpackov** [comment]
> The test script at cxx20-modules-examples/test compiles the source files and executes to completion if [...]

Hm, this script passes for me without this change with exactly the same compiler version.

> ./test g++ -fmodules-ts -std=c++23

Can you try just the following (and without your change above):

```
./test g++
```

(`build2` will pass all the necessary options automatically.)

**Comment by JungHong** [comment]
I just saw your reply.  There is no error from the following

git clone https://github.com/build2/cxx20-modules-examples.git
cd cxx20-modules-examples/
./test g++

Thank you.

**Comment by Klaim** [comment]
Closing this as it seems it's solved, feel free to reopen if not.
